/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registration.form;

import javax.swing.JOptionPane;

/**
 *
 * @author PC1
 */
public class Registration_Form extends javax.swing.JFrame {
    String Full_name, birthdate, email, Pcont, Adrs;
    
    
    public void submitted(){
        Full_name = Fname.getText()+ " " + Lname.getText();
        birthdate = Month.getText() + "-" + Day.getText() + "-" + Year.getText();
        email = Email.getText();
        Pcont = Pnum.getText();
        Adrs= adrs.getText();
        
        System.out.print("------------Registration Form------------\n"
                      + "First Name: " + Full_name + "\n"
                      + "Birthdate: " + birthdate + "\n"
                      + "Email: " + email + "\n"
                      + "Phone Contact: " + Pcont + "\n"
                      + "Address: " + Adrs + "\n"
                      + "------------------------------------------\n");
                       
    }
    
    /**
     * Creates new form Application
     */
    public Registration_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Month = new javax.swing.JTextField();
        Day = new javax.swing.JTextField();
        Year = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Pnum = new javax.swing.JTextField();
        Submit_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        adrs = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Registration Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        Fname.setText("First Name");
        Fname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FnameMousePressed(evt);
            }
        });
        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });
        getContentPane().add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 38, 136, -1));

        Lname.setText("Last Name");
        Lname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LnameMousePressed(evt);
            }
        });
        Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameActionPerformed(evt);
            }
        });
        getContentPane().add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 38, 136, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Full Name ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Birth Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, 56, -1));

        Month.setText("Month");
        Month.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MonthMousePressed(evt);
            }
        });
        getContentPane().add(Month, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 76, -1, -1));

        Day.setText("Day");
        Day.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DayMousePressed(evt);
            }
        });
        Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayActionPerformed(evt);
            }
        });
        getContentPane().add(Day, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 76, 36, -1));

        Year.setText("Year");
        getContentPane().add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 76, 48, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        Email.setText("ex: myName@example.com");
        Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmailMousePressed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 114, 158, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Cell phone Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, -1, -1));

        Pnum.setText("ex: 09*********");
        Pnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PnumMousePressed(evt);
            }
        });
        getContentPane().add(Pnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 152, 119, -1));

        Submit_button.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Submit_button.setText("Submit");
        Submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Submit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 262, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        getContentPane().add(adrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
  
    }//GEN-LAST:event_FnameActionPerformed

    private void LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameActionPerformed

    private void DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayActionPerformed

    private void Submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_buttonActionPerformed

        submitted();
        dispose();
        JOptionPane.showMessageDialog( null, "Submitted!!", "Done", 1);
        
        

    }//GEN-LAST:event_Submit_buttonActionPerformed

    private void FnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FnameMousePressed
        if (Fname.getText().equals("First Name")){
        Fname.setText("");
        }
    }//GEN-LAST:event_FnameMousePressed

    private void LnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LnameMousePressed
    if (Lname.getText().equals("Last Name")){
        Lname.setText("");
        }    }//GEN-LAST:event_LnameMousePressed

    private void MonthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthMousePressed
    if (Month.getText().equals("Month")){
        Month.setText("");
        }    }//GEN-LAST:event_MonthMousePressed

    private void DayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DayMousePressed
    if (Day.getText().equals("Day")){
        Day.setText("");
        }    }//GEN-LAST:event_DayMousePressed

    private void EmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailMousePressed
    if (Email.getText().equals("ex: myName@example.com")){
        Email.setText("");
        }    }//GEN-LAST:event_EmailMousePressed

    private void PnumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnumMousePressed
    if (Pnum.getText().equals("ex: 09*********")){
        Pnum.setText("");
        }    }//GEN-LAST:event_PnumMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Day;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Month;
    private javax.swing.JTextField Pnum;
    private javax.swing.JButton Submit_button;
    private javax.swing.JTextField Year;
    private javax.swing.JTextField adrs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
